Fix steam icon and description
pop-os/steam pull request #15
Opened 2024-04-19 17:46 UTC by mmstick

2024-04-19 18:41 UTC, jackpot51 approved these changes

2024-04-19 18:42 UTC, jackpot51 requested changes
`debian/patches/metainfo-Include-Debian-specific-advice.patch` needs to be dropped or modified to fix the appstream name

2024-04-19 19:08 UTC, jackpot51 approved these changes

2024-04-22 23:12 UTC, leviport approved these changes
Fixes icon in COSMIC DE, and the icon is still good in Gnome.

2024-04-23 17:15 UTC, merged